### ISSUE TITLE
NPCAddBuffTime vs. Star Cell kick

### ISSUE THREAD

**Issue by moisterrific** [Fe7n/TShockMobile#9]
For some reason using Daybreak and Solar Eruption causes the player to be kicked every time when fighting against Star Cell enemies. 

Also Stardust Cell minions too.

**Comment by Fe7n** [comment]
How about making the permitted buff time longer?

**Comment by moisterrific** [comment]
Making it longer does not fix it. I even tried setting it to 60 seconds but still get kicked.

**Comment by moisterrific** [comment]
"Fixed" in https://github.com/Fe7n/TShockMobile/commit/2176af135e77531835b962683223d2392c6622ae

**Comment by moisterrific** [comment]
pinpointed the issue to the `townNPC` check in `OnNPCAddBuff`

trying different ways to fix it

**Comment by moisterrific** [comment]
Fixed in https://github.com/Fe7n/TShockMobile/commit/6ce8d36dc60c71a99dee340fdf4868cf819e4eb5 (at the cost of ever so slightly compromised anti-cheat)
